INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME)
VALUES (-1, 'Joe', 'Bloggs');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME)
VALUES (-2, 'Joe', 'Bloggs');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME)
VALUES (-3, 'Joe', 'Bloggs');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME)
VALUES (-4, 'Joe', 'Bloggs');