CREATE SEQUENCE SEQ_ADDRESS;

CREATE TABLE ADDRESS
(
    ID          NUMBER NOT NULL DEFAULT SEQ_ADDRESS.NEXTVAL,
    PERSON_ID   NUMBER NOT NULL,
    STREET      VARCHAR2(800) NOT NULL,
    CITY        VARCHAR2(800),
    STATE       VARCHAR2(800),
    POSTAL_CODE VARCHAR2(50),
    COUNTRY     VARCHAR2(50) NOT NULL
);

ALTER TABLE ADDRESS
    ADD CONSTRAINT "PK_ADDRESS" PRIMARY KEY ("ID");
ALTER TABLE ADDRESS
    ADD CONSTRAINT "FK_PERSON" FOREIGN KEY ("PERSON_ID") REFERENCES PERSON ("ID");
