CREATE SEQUENCE SEQ_PERSON;

CREATE TABLE PERSON
(
    ID         NUMBER NOT NULL DEFAULT SEQ_PERSON.NEXTVAL,
    FIRST_NAME VARCHAR2(400) NOT NULL,
    LAST_NAME  VARCHAR2(400) NOT NULL
);

ALTER TABLE PERSON
    ADD CONSTRAINT "PK_PERSON" PRIMARY KEY ("ID");

